apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-options-ignorediff
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocdappdemo-ignorediff  
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Ignore_Diff
    repoURL: 'https://github.com/srikanthopsmx/ArgoCD-Complete-Master-Course.git'
    targetRevision: Practice
  ignoreDifferences:
    - kind: ConfigMap
      name: demo-configmap
      jsonPointers:
        - /data/key1  
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=false
